# Generated by Django 5.2.6 on 2025-10-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_average_review_remove_hotel_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(default='Unnamed Hotel', max_length=200),
        ),
    ]
