# Generated by Django 5.2.6 on 2025-10-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_alter_hotel_amenities'),
    ]

    operations = [
    ]
