# Generated by Django 5.2.6 on 2025-10-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_hotel_name'),
        ('hotels', '0005_auto_20251008_0121'),
    ]

    operations = [
    ]
