# Generated by Django 5.2.6 on 2025-10-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_merge_20251008_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
