# Generated by Django 5.2.7 on 2025-10-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_guest_dob_booking_guest_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('under_review', 'Under Review')], default='pending', max_length=20),
        ),
    ]
